### ISSUE TITLE
Reusing connection for other collections/queries

### ISSUE THREAD

**Issue by hongkongkiwi** [kof/socket.io-mongo#4]
Is there a way to get the mongodb client object from this plugin?

I'd hate to create another connection to the server but I want to query other collections as well.

**Comment by kof** [comment]
You should not use connection of this client because the current logic will close it when store is destroyed. Reuse of connection hasn't been considered yet.

Also consider this pull .... currently used mubsub version has a big bug.

https://github.com/kof/socket.io-mongo/pull/3/files

**Comment by oct8cat** [comment]
How about reverse the situation? is there a way to pass an already initiated connection to store's constructor? Let's say, I'm using [mongoose](http://mongoosejs.com) and it's already connected to mongo. It'd be cool to use mongoose's connection rather than open a new one.

**Comment by kof** [comment]
It is possible but needs some work to be done, also in mubsub.

Why do you care so much? It doesn't cost you lots of performance to have a separate connection ... it is probably even better to have mubsub communication over separate channel.

**Comment by oct8cat** [comment]
What if I'm using session storage, like [connect-mongo](https://github.com/kcbanner/connect-mongo), which requires it's own connection too? I was wondering if I able to have just one connection for all these storages. Btw, connect-mongo allows to use existing connection :D
